### ISSUE TITLE
[Feature] Unbounded Channel

### ISSUE THREAD

**Issue by zicklag** [stjepang/piper#15]
I'm having some trouble finding a channel that fits my requirements and so far I think Piper is the closest thing, but it needs an unbounded variant of the channel. Here are the requirements that need to be met to fit with my current project ( hopefully there aren't more, I'm still trying to refactor this project from sync to async and I haven't figured the whole thing out yet ):

- Needs to have bounded and unbounded variants
- The bounded and unbounded versions need to have the same Sender and Receiver structs ( I think I can work around this if necessary )
- The `send` ( and maybe `recv` too ) method needs to take non-mutable reference to `self`
- It needs to be multi-producer and I *think* it only needs to be single consumer.
- `Sender` needs to implement `Sync`.
- It needs to be awesome ( oh, I mean `async` )

Is this something we could add to `Piper`?

I've tried `futures-channel`, `flume`, `crossbeam-channel`, and all of them fail in one point or another, and I haven't found anything else.

**Comment by stjepang** [comment]
How would you feel about this API?

```rust
struct BoundedSender<T>;   // Clone + Send + Sync
struct UnboundedSender<T>; // Clone + Send + Sync
struct Receiver<T>;        // Clone + Send + Sync

impl<T> Sink<T> for UnboundedSender<T> {}
impl<T> Sink<T> for BoundedSender<T> {}
impl<T> Stream for Receiver<T> {}

fn bounded<T>(cap: usize) -> (Sender<T>, Receiver<T>);
fn unbounded<T>() -> (Sender<T>, Receiver<T>);

impl<T> UnboundedSender<T> {
    fn try_send(&self, msg: T) -> Result<(), TrySendError<T>>;
    fn send(&self, msg: T) -> Result<(), SendError<T>>;
}

impl<T> BoundedSender<T> {
    fn try_send(&self, msg: T) -> Result<(), TrySendError<T>>;
    async fn send(&self, msg: T) -> Result<(), SendError<T>>;
}

impl<T> Receiver<T> {
    fn try_recv(&self) -> Result<T, TryRecvError>;
    async fn recv(&self) -> Result<T, RecvError>;
}
```

**Comment by zicklag** [comment]
I think that looks good, but I have one question.

In my app I have actors that need to send messages to each-other, and the Actor struct contains the sender. My question is what is the best approach having actors use either a Bounded or an Unbounded sender without using Generics. I tried to make the actors generic over the sender, but it got super messy and I think it might not even be possible, at least without some real convolution in this particular code-base at least.

I considered an enum:

```rust
enum Sender<T> {
  Bounded(BoundedSender<T>),
  Unbounded(UnboundedSender<T>),
}

impl<T> Sender<T> {
  fn try_send() // etc.
  async fn send() // etc.
}
```

But in that case I don't know how expensive the `match` on the sender type that I have to do every single time I `send` is. Would that be no problem?

Otherwise, would there be a way to unify the sender types? That would probably make the sender heavier than it needed to be for one type or the other, though...

**Comment by stjepang** [comment]
The reason why I proposed here splitting them is because `UnboundedSend::send()` then doesn't need to be an async function.

But we can also unify sender types into a single `Sender` type that has an async `send()` method. That might be slightly annoying when using `Sender` in synchronous Rust, but can be solved either with `block_on()`, `.now_or_never()`, or by using `try_send()` instead.

**Comment by zicklag** [comment]
Because this crate is kind of targeted to async I think that maybe a `send_sync` function would not be too bad.

Another thought I just had, what if you put the functions in a trait such as `AsyncSender` and `SyncSender` and both would define a `send()` function and `Sender` would implement both. The user would then bring into scope whatever trait they wanted to use and they would just call the `send()` function. That does kind of make it harder to tell just by looking at the function call whether or not it is the sync or the async version.

---

I'm leaning towards just adding a `send_sync`. That way it is most natural to call the `async` `send()` function and you don't accidentally call a sync version in `async` code, but it isn't easy to accidentally call the async version in `sync` code because you would get a future instead of a message and will get a compiler error if you try to use it.

**Comment by stjepang** [comment]
async-channel can be unbounded: https://github.com/stjepang/async-channel
