### ISSUE TITLE
Possibly expose Event

### ISSUE THREAD

**Issue by dignifiedquire** [stjepang/piper#2]
`Event` seems like a very nice building block. Could be very useful to be exposed, so other primitives could be implemented based on it.

**Comment by jjl** [comment]
I've currently applied the following (very small) patch to piper locally so I can play with it

```
diff --git a/src/lib.rs b/src/lib.rs
index c7ae1ed..e8f4522 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -4,7 +4,7 @@
 
 mod arc;
 mod chan;
-mod event;
+pub mod event;
 mod lock;
 mod mutex;
 mod pipe;

```

**Comment by jjl** [comment]
I think this is a very useful building block that could possibly do with its own crate, as async-task has its own crate.

**Comment by zicklag** [comment]
`Event` is *exactly* what I'm looking for. I need a way to allow tasks to wait on a system shutdown, but a channel is not suitable like the example in the `smol` docs because it doesn't allow other tasks that don't want to wait to simply *check* the shutdown state.

**Comment by stjepang** [comment]
Sounds good, I'll expose `Event` as a public type.

**Comment by stjepang** [comment]
Moved into https://docs.rs/event-listener/
