### ISSUE TITLE
Piper channel slower in benchmarks

### ISSUE THREAD

**Issue by tekjar** [stjepang/piper#20]
Hi @stjepang. I was replacing tokio channel with piper's and observed a perf degrade in one of my crates. I decided to run a small benchmark

```
running 2 tests
test test::spsc_1000000_smol  ... bench:  39,495,596 ns/iter (+/- 219,797)
test test::spsc_1000000_tokio ... bench:  26,520,332 ns/iter (+/- 312,603)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured; 0 filtered out
```

Is this difference to be expected?

[code](https://github.com/tekjar/numbers/blob/master/channels/src/main.rs)

**Comment by stjepang** [comment]
That is because the benchmark is only measuring the speed of `try_recv()` when the channel is empty :)

Note that in the benchmark a thread does 1M sends, but then the benchmark iteration loop does 1M receive operations many more times. So during the benchmark the channel is almost always empty.

**Comment by tekjar** [comment]
> So during the benchmark the channel is almost always empty

Ah crap. Yeah

Here are the updated results after moving tx inside bench iter (in case people find this issue in future)

```
test test::spsc_1000000_smol  ... bench: 191,194,968 ns/iter (+/- 43,485,778)
test test::spsc_1000000_tokio ... bench: 387,106,076 ns/iter (+/- 14,055,810)
```

> I was replacing tokio channel with piper's and observed a perf degrade in one of my crates

The only other difference I could think of in my actual application is using `now_or_never` 

```
if let Err(e) = connection.handle.try_send(reply) {
     error!("Failed to data reply. Error = {:?}", e.to_string());
}

vs

if connection.handle.send(reply).now_or_never().is_none() {
    error!("Failed to topics refresh reply");
}
```

Is there any extra synchronization overhead with `now_or_never` when compared with `try_send`?

**Comment by stjepang** [comment]
Yes, `now_or_never()` is slower than `try_send()`:

* `try_send()` just attempts a send operation and if it fails, we're done.
* `now_or_never()` will poll the `send()` future, so if sending fails, we'll register the current task's waker, and then `now_or_never()` will drop the future, which means we deregister the current task's waker.

So `now_or_never()` does the extra waker registration and deregistration.

**Comment by tekjar** [comment]
Thanks for that explanation :). Is there any design hurdle in piper having `try_send`?

**Comment by stjepang** [comment]
Not really, I think I'll just redesign the API a bit to make it match crossbeam-channel...

**Comment by tekjar** [comment]
Nice. Thanks!!
