### ISSUE TITLE
Question: Why wrap Lock in an inner Arc? 

### ISSUE THREAD

**Issue by dignifiedquire** [stjepang/piper#3]
I understand it adds easy `Clone`ability, but it removes the ability to implement `into_inner` on it. But if the `Arc` is not there you can wrap the outer, if clone is needed, as a user, and still get `into_inner` on the library version.

**Comment by stjepang** [comment]
The reason is that this allows us to send `LockGuard` to a different task because it's not tied by a lifetime to the parent `Lock`. This prevents us from implementing `into_inner()` because the lock may be held at any point.

**Comment by stjepang** [comment]
I assume this question was answered? Closing, but let me know if not!

**Comment by dignifiedquire** [comment]
It was, thank you
